admin_domain: "patrykarc.tojest.dev"
api_domain: "patrykapi.tojest.dev"
next_revalidate_url: "https://arch-hub-tawny.vercel.app"
app_dir: "/home/ahdeploy/architecture-hub-showcase"
app_user: "ahdeploy"
ghcr_owner: "patrykostrzolek"
certbot_webroot: "/var/www/certbot"
