version: '3'

services:
  php:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8080"
    environment:
      PHP_OPCACHE_ENABLE: 1
    volumes:
      - .:/var/www/html
      - ./docker/nginx/server-opts.d/sulu-homepage-json.conf:/etc/nginx/server-opts.d/sulu-homepage-json.conf:ro
###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432:5432"
###< doctrine/doctrine-bundle ###
