<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260701184007 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create exercise_attempt table for the Assessment bounded context (ADR-0012).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE exercise_attempt (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, exercise_uuid VARCHAR(36) NOT NULL, session_id VARCHAR(36) NOT NULL, answers JSON NOT NULL, score INT NOT NULL, total INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_exercise_attempt_exercise_uuid ON exercise_attempt (exercise_uuid)');
        $this->addSql('CREATE INDEX IDX_exercise_attempt_session_id ON exercise_attempt (session_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE exercise_attempt');
    }
}
