<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260702144733 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create Question/Option/QuestionSet/QuestionSetItem tables for the Assessment bounded context (ADR-0014).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE assessment_option (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, text TEXT NOT NULL, is_correct BOOLEAN NOT NULL, position INT NOT NULL, question_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AE5B91DE1E27F6BF ON assessment_option (question_id)');
        $this->addSql('CREATE TABLE assessment_question (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, text TEXT NOT NULL, explanation TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE assessment_question_set (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE assessment_question_set_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position INT NOT NULL, question_set_id INT NOT NULL, question_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5B7695AC17A62210 ON assessment_question_set_item (question_set_id)');
        $this->addSql('CREATE INDEX IDX_5B7695AC1E27F6BF ON assessment_question_set_item (question_id)');
        $this->addSql('ALTER TABLE assessment_option ADD CONSTRAINT FK_AE5B91DE1E27F6BF FOREIGN KEY (question_id) REFERENCES assessment_question (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE assessment_question_set_item ADD CONSTRAINT FK_5B7695AC17A62210 FOREIGN KEY (question_set_id) REFERENCES assessment_question_set (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE assessment_question_set_item ADD CONSTRAINT FK_5B7695AC1E27F6BF FOREIGN KEY (question_id) REFERENCES assessment_question (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE assessment_option DROP CONSTRAINT FK_AE5B91DE1E27F6BF');
        $this->addSql('ALTER TABLE assessment_question_set_item DROP CONSTRAINT FK_5B7695AC17A62210');
        $this->addSql('ALTER TABLE assessment_question_set_item DROP CONSTRAINT FK_5B7695AC1E27F6BF');
        $this->addSql('DROP TABLE assessment_option');
        $this->addSql('DROP TABLE assessment_question');
        $this->addSql('DROP TABLE assessment_question_set');
        $this->addSql('DROP TABLE assessment_question_set_item');
    }
}
