---
- name: Provision server
  hosts: web
  become: true

  vars_files:
    - ../group_vars/all/main.yml
    - ../group_vars/all/vault.yml
    - "../group_vars/{{ 'primary' if 'primary' in group_names else 'secondary' }}/main.yml"

  roles:
    - common
    - docker
    - tailscale
    - nginx
    - { role: certbot, when: not is_primary }
